name = "posta"
main = "src/index.ts"
compatibility_date = "2026-08-01"

routes = [
  { pattern = "posta.gpro.my.id/*", zone_name = "gpro.my.id" },
  { pattern = "*.posta.gpro.my.id/*", zone_name = "gpro.my.id" }
]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "posta"
database_id = "1ef8cd6d-4b17-4199-b1c8-2ca5780f048a"
